// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNnRk1KJxwyTCqA6NOpjI8-MBVRnyAulM',
    appId: '1:24514503294:web:20850655a4f3323bbbae2f',
    messagingSenderId: '24514503294',
    projectId: 'kucognition-app-8cf64',
    authDomain: 'kucognition-app-8cf64.firebaseapp.com',
    storageBucket: 'kucognition-app-8cf64.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm3_kTUhmipAFbpO4JaBBd7JUnuyveSuI',
    appId: '1:24514503294:android:2ebedc924655d875bbae2f',
    messagingSenderId: '24514503294',
    projectId: 'kucognition-app-8cf64',
    storageBucket: 'kucognition-app-8cf64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBezzkAsA4BV2i6f7b8pbwm_SnitEwF5bQ',
    appId: '1:24514503294:ios:8d820cc7cfc36e88bbae2f',
    messagingSenderId: '24514503294',
    projectId: 'kucognition-app-8cf64',
    storageBucket: 'kucognition-app-8cf64.firebasestorage.app',
    iosBundleId: 'com.example.kucognitionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBezzkAsA4BV2i6f7b8pbwm_SnitEwF5bQ',
    appId: '1:24514503294:ios:8d820cc7cfc36e88bbae2f',
    messagingSenderId: '24514503294',
    projectId: 'kucognition-app-8cf64',
    storageBucket: 'kucognition-app-8cf64.firebasestorage.app',
    iosBundleId: 'com.example.kucognitionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNnRk1KJxwyTCqA6NOpjI8-MBVRnyAulM',
    appId: '1:24514503294:web:e12e7116e408084bbbae2f',
    messagingSenderId: '24514503294',
    projectId: 'kucognition-app-8cf64',
    authDomain: 'kucognition-app-8cf64.firebaseapp.com',
    storageBucket: 'kucognition-app-8cf64.firebasestorage.app',
  );

}