// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnUfaOVkC7QCyzNd31z5-jVBo-owPERvU',
    appId: '1:222093951130:web:c8ebd24701207723901f23',
    messagingSenderId: '222093951130',
    projectId: 'kucognition-app',
    authDomain: 'kucognition-app.firebaseapp.com',
    storageBucket: 'kucognition-app.firebasestorage.app',
    measurementId: 'G-748SSBKBY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVgboq5lXFm9Ap3AcPx7uQZQbDm0QkXNU',
    appId: '1:222093951130:android:e1adae79cca6a90c901f23',
    messagingSenderId: '222093951130',
    projectId: 'kucognition-app',
    storageBucket: 'kucognition-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH3V6UvgNaXo-jgNmFB6953x9u6O7hzE0',
    appId: '1:222093951130:ios:2a545e174619de78901f23',
    messagingSenderId: '222093951130',
    projectId: 'kucognition-app',
    storageBucket: 'kucognition-app.firebasestorage.app',
    iosBundleId: 'com.example.kucognitionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH3V6UvgNaXo-jgNmFB6953x9u6O7hzE0',
    appId: '1:222093951130:ios:2a545e174619de78901f23',
    messagingSenderId: '222093951130',
    projectId: 'kucognition-app',
    storageBucket: 'kucognition-app.firebasestorage.app',
    iosBundleId: 'com.example.kucognitionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnUfaOVkC7QCyzNd31z5-jVBo-owPERvU',
    appId: '1:222093951130:web:e447eca432859fed901f23',
    messagingSenderId: '222093951130',
    projectId: 'kucognition-app',
    authDomain: 'kucognition-app.firebaseapp.com',
    storageBucket: 'kucognition-app.firebasestorage.app',
    measurementId: 'G-T5FRR3FPMQ',
  );
}
